RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Areas/Admin/Models/Formulaires/CreateProjetForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _WebApp.Areas.Admin.Models.Formulaires {
    public class CreateProjetForm {

        public string Nom { get; set; }
        public string Description { get; set; }
        public DateTime DateDebut { get; set; }
        public DateTime? DateFin { get; set; }
    }
}

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Models/Formulaires/ProjetForms.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _WebApp.Models.Formulaires
{
    public class ProjetForms
    {
        [Required]
        [MaxLength(50)]
        public string Nom { get; set; }

        [Required]
        [MaxLength(250)]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        [Required]
        [DisplayFormat(DataFormatString = "{dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date de début")]
        public DateTime Debut { get; set; }

        [DataType(DataType.Date)]
        [Required]
        [DisplayFormat(DataFormatString = "{dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date de Fin")]
        public DateTime? Fin { get; set; }

        public int? Admin { get; set; }
    }
}

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Controllers/MemberController.cs
using _WebApp.Infrastructure;
using _WebApp.Models.Formulaires;
using _WebApp.Models.ViewModels;
using Client.Models;
using Client.Services;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace _WebApp.Controllers
{
    [AuthRequired]
    public class MemberController : Controller
    {
        public ActionResult Index()
        {
            MemberIndex mi = new MemberIndex();
            int idEmp = (int) EmployeeSession.CurrentEmployee.Id;

            ProjetService ps = new ProjetService();
            mi.ListP = ps.GetListByIdEmpl(idEmp);

            EmployeeService es = new EmployeeService();
            mi.ListE = es.GetByEquipe(idEmp);

            mi.ListEWDiscussion = es.GetWithDiscussion(idEmp);

            MessageEmployeeService mes = new MessageEmployeeService();
            mi.ListME = mes.GetAll();

            return View(mi);
        }

        
        /***********************************************************************************************************
         ***********************************************Equipe******************************************************
         ***********************************************************************************************************/
        //public ActionResult Equipe()
        //{
        //    EmployeeService es = new EmployeeService();
        //    return View(es.GetByEquipe((int) EmployeeSession.CurrentEmployee.Id).First().Id);
        //}

        public ActionResult Equipe()
        {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;
                           
            MemberEquipe me = new MemberEquipe();

            EquipeService eqs = new EquipeService();
            Equipe eq = eqs.GetByEmployee(idMoi);

            if (eq != null) {
                int? idEq = eq.Id;

                if (idEq != null && idEq != 0) {
                    /*EmployeeService ems = new EmployeeService();
                    //Verifie si l'utilisateur courrant a accès à l'équipe 'idEq'
                    Employee e = ems.GetByEquipe((int)idEq).Where(r => r.Id == idMoi).SingleOrDefault();

                    if (e != null) {*/
                        me.eq = eqs.GetById((int)idEq);

                        EmployeeService es = new EmployeeService();
                        me.ListE = es.GetByEquipe((int)idEq);

                        MessageEquipeService mes = new MessageEquipeService();
                        me.ListMEq = mes.GetSujetByEquipe((int)idEq);

                        DocumentService ds = new DocumentService();
                        me.ListD = ds.GetByEquipe((int)idEq);

                        //TODO Chef d'équipe
                        //me.emp = es.GetManagerByEquipe((int)idEq);

                        return View(me);
                    //}
                }
            }
            return RedirectToAction("Index", "Error");
        }

        /***********************************************************************************************************
         ***********************************************Employee****************************************************
         ***********************************************************************************************************/
        public ActionResult Employee(int id) {
            MemberDiscussion md = new MemberDiscussion();

            EmployeeService es = new EmployeeService();
            md.employee = es.GetById(id);

            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;
            MessageEmployeeService mes = new MessageEmployeeService();

            md.ListeMessageEmployees = mes.GetDiscution(idMoi, id);

            return View(md);
        }

        /***********************************************************************************************************
         ************************************************Projet*****************************************************
         ***********************************************************************************************************/
        //public ActionResult Projet() {
        //    int IdEmp = (int)EmployeeSession.CurrentEmployee.Id;
        //    ProjetService ps = new ProjetService();
        //    return View(ps.GetByIdEmpl(IdEmp).First().Id);
        //}

        public ActionResult Projet(int id = 0)
        {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;
            
            MemberProjet mp = new MemberProjet();
            ProjetService ps = new ProjetService();

            if (id == 0) {
                //Récupere le premier projet de l'utilisateur
                Projet p = ps.GetByIdEmpl(idMoi).FirstOrDefault();

                if (p != null && p.Id != null) {
                    mp.p = p;
                    id = (int)p.Id;
                }
                else {
                    //Aucun projet assigner
                    return RedirectToAction("Index", "Member");
                }
            }
            else {
                mp.p = ps.GetById(id);
            }

            EmployeeService ems = new EmployeeService();
            //Verifie si l'utilisateur courrant a accès au projet 'id'
            Employee e = ems.GetByProjet(id).Where(r => r.Id == idMoi).SingleOrDefault();

            if (e != null) {
                mp.chef = ems.GetManagerByProjet(id);

                TacheEmployeeService tes = new TacheEmployeeService();
                mp.TacheEmployees = tes.GetByEmployee(idMoi);

                TacheEquipeService teq = new TacheEquipeService();
                mp.TacheEquipes = teq.GetByProjet(id);

                MessageProjetService mps = new MessageProjetService();
                mp.MessageProjets = mps.GetSujetByProjet(id);

                DocumentService ds = new DocumentService();
                mp.Documents = ds.GetByProjet(id);

                return View(mp);
            }
            return RedirectToAction("Index", "Error");
        }

        //public ActionResult CreateProjet()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult CreateProjet(ProjetForms form)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        Projet p = new Projet(form.Nom, form.Description, form.Debut, form.Fin, form.Admin);
        //        ProjetService ps = new ProjetService();
        //        ps.Insert(p);

        //        return RedirectToAction("Index", "Member");
        //    }
        //    return View(form);
        //}

        /***********************************************************************************************************
         ***********************************************Taches******************************************************
         ***********************************************************************************************************/

        public ActionResult TacheEquipe(int id) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;
            
            EmployeeService ems = new EmployeeService();
            //Verifie si l'utilisateur courrant a accès a la tache equipe 'id'
            Employee e = ems.GetByTacheEquipe(id).Where(r => r.Id == idMoi).SingleOrDefault();

            if (e != null) {
                MemberTacheEquipe mteq = new MemberTacheEquipe();

                TacheEquipeService teqs = new TacheEquipeService();
                mteq.te = teqs.GetById(id);

                MessageTacheService mteqq = new MessageTacheService();
                mteq.ListM = mteqq.GetSujetByTacheId(id);

                DocumentService ds = new DocumentService();
                mteq.ListD = ds.GetByTache(id);

                return View(mteq);
            }
            return RedirectToAction("Index", "Error");
        }
        public ActionResult TacheEmployee(int id) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;
            
            EmployeeService ems = new EmployeeService();
            //Verifie si l'utilisateur courrant a accès a la tache employee 'id'
            Employee e = ems.GetByTacheEmployee(id).Where(r => r.Id == idMoi).SingleOrDefault();

            if (e != null) {
                MemberTacheEmployee mte = new MemberTacheEmployee();

                TacheEmployeeService teqs = new TacheEmployeeService();
                mte.te = teqs.GetById(id);

                MessageTacheService mtes = new MessageTacheService();
                mte.ListM = mtes.GetSujetByTacheId(id);

                DocumentService ds = new DocumentService();
                mte.ListD = ds.GetByTache(id);

                return View(mte);
            }
            return RedirectToAction("Index", "Error");
        }
    }
}

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Controllers/MessageController.cs
using _WebApp.Infrastructure;
using _WebApp.Models.Formulaires;
using Client.Models;
using Client.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _WebApp.Controllers
{
    public class MessageController : Controller
    {
        // GET: Message
        public ActionResult Index()
        {
            return View();
        }

        /***********************************************************************************************************
         ***********************************************Message*****************************************************
         ***********************************************************************************************************/

        public ActionResult MessageEquipe(int id) {
            MessageEquipeService mes = new MessageEquipeService();

            return View(mes.GetMessageBySujet(id));
        }

        public ActionResult MessageProjet(int id) {
            MessageProjetService mps = new MessageProjetService();

            return View(mps.GetMessageBySujet(id));
        }

        public ActionResult MessageTacheEquipe(int id) {
            MessageTacheService mts = new MessageTacheService();

            return View(mts.GetMessageBySujet(id));
        }

        /***********************************************************************************************************
         *******************************************RéponseMessage**************************************************
         ***********************************************************************************************************/

        [HttpPost]
        public ActionResult RepondreEmployee(int idDest, int? idMsg, string msg) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (!string.IsNullOrWhiteSpace(msg) && idDest != 0) {
                MessageEmployee me = new MessageEmployee { Titre = idMoi + "" + idDest, Contenu = msg, Date = DateTime.Now, Id_Employee = idMoi, Id_Destinataire = idDest, MessagePrecedent = idMsg };

                MessageEmployeeService mes = new MessageEmployeeService();
                mes.Insert(me);
            }

            return RedirectToAction("Employee", "Member", new { id = idDest });
        }

        [HttpPost]
        public ActionResult RepondreEquipe(int idEq, int? idMsg, string msg) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (!string.IsNullOrWhiteSpace(msg) && idEq != 0) {
                MessageEquipe me = new MessageEquipe { Titre = idMoi + "" + idEq, Contenu = msg, Date = DateTime.Now, Id_Employee = idMoi, Id_Equipe = idEq, MessagePrecedent = idMsg };

                MessageEquipeService mes = new MessageEquipeService();
                mes.Insert(me);
            }

            return RedirectToAction("Equipe", "Member", new { id = idEq });
        }

        [HttpPost]
        public ActionResult RepondreProjet(int idPr, int? idMsg, string msg) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (!string.IsNullOrWhiteSpace(msg) && idPr != 0) {
                MessageProjet mp = new MessageProjet { Titre = idMoi + "" + idPr, Contenu = msg, Date = DateTime.Now, Id_Employee = idMoi, Id_Projet = idPr, MessagePrecedent = idMsg };

                MessageProjetService mps = new MessageProjetService();
                mps.Insert(mp);
            }

            return RedirectToAction("Projet", "Member", new { id = idPr });
        }

        [HttpPost]
        public ActionResult RepondreTacheEmployee(int idTa, int? idMsg, string msg) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (!string.IsNullOrWhiteSpace(msg) && idTa != 0) {
                MessageTache mt = new MessageTache { Titre = idMoi + "" + idTa, Contenu = msg, Date = DateTime.Now, Id_Employee = idMoi, Id_Tache_Employee = idTa, Id_Tache_Equipe = null, MessagePrecedent = idMsg };

                MessageTacheService mps = new MessageTacheService();
                mps.Insert(mt);
            }

            return RedirectToAction("TacheEmployee", "Member", new { id = idTa });
        }

        [HttpPost]
        public ActionResult RepondreTacheEquipe(int idTa, int? idMsg, string msg) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (!string.IsNullOrWhiteSpace(msg) && idTa != 0) {
                MessageTache mt = new MessageTache { Titre = idMoi + "" + idTa, Contenu = msg, Date = DateTime.Now, Id_Employee = idMoi, Id_Tache_Employee = null, Id_Tache_Equipe = idTa, MessagePrecedent = idMsg };

                MessageTacheService mps = new MessageTacheService();
                mps.Insert(mt);
            }

            return RedirectToAction("TacheEquipe", "Member", new { id = idTa });
        }

        /***********************************************************************************************************
         *********************************************NouveauSujet**************************************************
         ***********************************************************************************************************/

        public ActionResult CreateSujetEquipe(int id) {
            TempData["idEq"] = id;
            return View();
        }

        [HttpPost]
        public ActionResult CreateSujetEquipe(SujetForm form) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (ModelState.IsValid) {
                MessageEquipeService mes = new MessageEquipeService();
                MessageEquipe me = new MessageEquipe(form.Titre, DateTime.Now, form.Message, null, idMoi, (int)TempData["idEq"], null);

                mes.Insert(me);
                return RedirectToAction("Equipe", "Member");
            }
            return View(form);
        }

        public ActionResult CreateSujetProjet(int id) {
            TempData["idPr"] = id;
            return View();
        }

        [HttpPost]
        public ActionResult CreateSujetProjet(SujetForm form) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (ModelState.IsValid) {
                MessageProjetService mps = new MessageProjetService();
                MessageProjet mp = new MessageProjet(form.Titre, DateTime.Now, form.Message, null, idMoi, (int)TempData["idPr"], null);

                mps.Insert(mp);
                return RedirectToAction("Projet", "Member");
            }
            return View(form);
        }

        public ActionResult CreateSujetTache(int id) {
            TempData["idPr"] = id;
            return View();
        }

        [HttpPost]
        public ActionResult CreateSujetTacheEquipe(SujetForm form) {
            int idMoi = (int)EmployeeSession.CurrentEmployee.Id;

            if (ModelState.IsValid) {
                MessageTacheService mts = new MessageTacheService();
                MessageTache mt = new MessageTache(form.Titre, DateTime.Now, form.Message, null, idMoi, (int)TempData["idPr"], null, null);

                mts.Insert(mt);
                return RedirectToAction("TacheEquipe", "Member");
            }
            return View(form);
        }
    }
}

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Views/Member/DeleteProjet.cshtml
@model Client.Models.Projet

@{
    ViewBag.Title = "DeleteProjet";
}

<h2>DeleteProjet</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Debut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Views/Member/Equipe.cshtml
@using Client.Models
@model _WebApp.Models.ViewModels.MemberEquipe

@{
    ViewBag.Title = "Equipe";
}

<h2>DétailsEquipe</h2>

@if (Model.eq != null) {
<div>
    <h4>Equipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.eq.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eq.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.eq.Creee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.eq.Creee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp.Prenom)
        </dd>
    </dl>
</div>

<div class="list-group">
    <h4>Employee</h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.emp.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.emp.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.emp.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.emp.Tel)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.ListE) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tel)
                </td>

                <td>
                    @Html.ActionLink("Détails", "Employee", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

<div class="list_message">
    <h4>Messages d'équipe</h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.msgeq.Titre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.msgeq.Auteur)
            </th>
        </tr>
        @foreach (var item in Model.ListMEq) {
            <tr>
                <td>
                    @Html.ActionLink(item.Titre.ToString(), "MessageEquipe", "Message", new { id = item.Id}, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Auteur)
                </td>
            </tr>
        }
    </table>
    <p>
        @Html.ActionLink("Nouveau sujet", "CreateSujetEquipe", "Message", new { id = Model.eq.Id}, null)
    </p>
</div>

<div class="list-group">
    <h4 class="menumilieu">Documents</h4>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.d.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.d.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.d.Lien)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.ListD) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lien)
                </td>
            </tr>
        }

    </table>
</div>
}
else {
    <p>Vous n'êtes actuellement dans aucune équipe</p>
}

<p>
    @Html.ActionLink("Retour", "Index")
</p>

RSE.NET BACKUP 23-10-18 09h49m/_WebApp/Views/Member/Projet.cshtml
@model _WebApp.Models.ViewModels.MemberProjet

@{
    ViewBag.Title = "Projet";
}

<div class="detproj">
    <h2>DetailsProjet</h2>

    @if (Model.chef != null) {
        <div>
            <h4>Projet</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.p.Nom)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.p.Nom)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.p.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.p.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.p.Debut)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.p.Debut)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.p.Fin)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.p.Fin)
                </dd>

                <dt>
                    Chef de Projet
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.chef.Nom)  @Html.DisplayFor(model => model.chef.Prenom)
                </dd>
            </dl>
        </div>

        <div class="list-group">
            <h4>Taches employée</h4>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Nom)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Debut)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Fin)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.TacheEmployees) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Debut)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fin)
                        </td>
                        <td>
                            @Html.ActionLink("Détails", "TacheEmployee", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>

        <div class="list-group">
            <h4>Taches équipe</h4>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Nom)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Debut)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.t.Fin)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.TacheEquipes) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Debut)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fin)
                        </td>
                        <td>
                            @Html.ActionLink("Détails", "TacheEquipe", new { id = item.Id })
                        </td>
                    </tr>
                }

            </table>
        </div>

        <div class="list-group">
            <h4>Messages du projet</h4>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.mp.Titre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.mp.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.mp.Contenu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.mp.Auteur)
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model.MessageProjets) {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Titre.ToString(), "MessageProjet", "Message", new { id = item.Id }, null)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Contenu)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Auteur)
                        </td>
                    </tr>
                }
            </table>
            <p>
                @Html.ActionLink("Nouveau sujet", "CreateSujetProjet", "Message", new { id = Model.p.Id}, null)
            </p>
        </div>
        
        <div class="list-group">
            <h4 class="menumilieu">Documents</h4>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.d.Nom)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.d.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.d.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.d.Taille)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.d.Lien)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Documents) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nom)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Taille)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lien)
                        </td>
                    </tr>
                }

            </table>
        </div>
    }

    else {
        <p>Vous n'êtes actuellement affecter à aucun projet</p>
    }
</div>
<p>
    @Html.ActionLink("Retour", "Index")
</p>